### ISSUE TITLE
'GetSnapshot' API can not working properly because of configuration

### ISSUE THREAD

**Issue by 447264188** [edgexfoundry-holding/device-onvif-camera#132]
### Summary of the problem:
'GetSnapshot' API can not working properly

###  Issue reproducible on below camera models:
HIKVISION-DS-2DC4223IW-DE
HIKVISION-DS-2CD3T27FWDA4-LS
### Tester
from ThunderSoft

### Reproduce steps:
Execute this command

configuration.toml 
```toml
    [Writable.InsecureSecrets.Camera001]
    path = "default"
      [Writable.InsecureSecrets.Camera001.Secrets]
      username = "admin"
      password = "123456"
      mode = "both" # assign "digest" | "usernametoken" | "both" | "none"
```
The test script is as follows:

```bash
curl --location --request GET 'http://10.0.20.42:59882/api/v2/device/name/HIKVISION-DS-2DC4223IW-DE-3bd4c000-b1b9-11b3-8202-4cf5dc64a22c/Snapshot'
```
The error message is as follows:

```json
{
    "apiVersion": "v2",
    "message":"request failed, status code: 500, err: {\"apiVersion\":\"v2\",\"message\":\"error reading DeviceResourece Snapshot for HIKVISION-DS-2DC4223IW-DE-3bd4c000-b1b9-11b3-8202-4cf5dc64a22c -\> failed to execute read command -\> http request for image failed with status 401, \<!DOCTYPE html\>\\r\\n\<html\>\<head\>\<title\>Document Error: Unauthorized\</title\>\</head\>\\r\\n\<body\>\<h2\>Access Error: 401 -- Unauthorized\</h2\>\\r\\n\<p\>Authentication Error: Digest authentication information verification failed\</p\>\\r\\n\</body\>\\r\\n\</html\>\\r\\n\",\"statusCode\":500}",
    "statusCode": 500
}
```

then the log is 
``` logs
level=ERROR ts=2022-08-23T12:05:21.08698713Z app=device-onvif-camera source=restrouter.go:158 X-Correlation-ID=fcb61d5c-7f48-4ef1-b368-f81081f47ee6 msg="error reading DeviceResourece Snapshot for HIKVISION-DS-2CD3T27FWDA4-LS-9b7f0000-0d7d-11b3-8131-40acbf7e7527 -> failed to execute read command -> failed to create 'GetProfiles' response for the web service 'Media' -> expected element type <Envelope> but have <html>"
```
And other APIs can get results normally
